### ISSUE TITLE
Апдейт мод-листа 

### ISSUE THREAD

**Issue by c1p-it** [stalker-thread/stalker-thread.github.io#12]
Братан, на просторах рунета сыскал потрясающий мод для ТЧ на основе OGSR Engine, который качественно дополняет ванилу — MonolithUI. Сунь ссылку на него в соответствующий раздел на сайте, если ты не против. И еще, т.к. для этого мода требуется OGSR, то считаю нужным залить куда-нибудь еще и ссылку на репозиторий этого движка, ибо новые релизы там выходят постоянно

https://disk.yandex.ru/d/uVuRR2kPAsB2Ew — MonolithUI
https://github.com/OGSR/OGSR-Engine — репозиторий OGSR Engine.

![image](https://user-images.githubusercontent.com/33309477/123944111-dae5e080-d9ad-11eb-96c7-b7954c1ffd6b.png)
![image](https://user-images.githubusercontent.com/33309477/123944128-de796780-d9ad-11eb-9a9f-d076f39d6beb.png)

**Comment by stalker-thread** [comment]
done
