### ISSUE TITLE
Оформление текста по бомбежу о действиях ПЫС и шифре

### ISSUE THREAD

**Issue by c1p-it** [stalker-thread/stalker-thread.github.io#4]
Братан, согласишься как-нибудь принять от меня грамматически правленый текст по тематике шифра и обсёров ПЫС? А то выглядит это всё как-то по-колхозному. Нужно сохранять лицо.

**Comment by stalker-thread** [comment]
А то ж. Пили, приму.

**Comment by c1p-it** [comment]
> А то ж. Пили, приму.

Держи, братан. Плюс добавил ссылки к постам на архивач по поводу слитых 3D моделей и договоре об NDA
https://pastebin.com/UJR3pViG

**Comment by stalker-thread** [comment]
Окей, пасиб. Перенесу, когда появится время

**Comment by stalker-thread** [comment]
Добавил правки. Задеплоится через некоторое время
