### ISSUE TITLE
Очепятка

### ISSUE THREAD

**Issue by c1p-it** [stalker-thread/stalker-thread.github.io#6]
Братан, фиксани в сталкер 2 факе на "15 мая"
![image](https://user-images.githubusercontent.com/33309477/104835174-3e77c800-58be-11eb-834f-af06d1490e98.png)

И еще, если посчитаешь нужным, под этой строчкой добавь пикчу-заглушку 
![image](https://user-images.githubusercontent.com/33309477/104835194-61a27780-58be-11eb-9298-a11a1f232f84.png)

**Comment by stalker-thread** [comment]
Спасибо, исправил. Сайт обновится через некоторое время

**Comment by c1p-it** [comment]
> Братан, фиксани в сталкер 2 факе на "15 мая"
> ![image](https://user-images.githubusercontent.com/33309477/104835174-3e77c800-58be-11eb-834f-af06d1490e98.png)
> 
> И еще, если посчитаешь нужным, под этой строчкой добавь пикчу-заглушку
> ![image](https://user-images.githubusercontent.com/33309477/104835194-61a27780-58be-11eb-9298-a11a1f232f84.png)
