### ISSUE TITLE
Сталкер 2 фак

### ISSUE THREAD

**Issue by c1p-it** [stalker-thread/stalker-thread.github.io#7]
Под строчкой
>Также в трейлере был обнаружен отрывок поэмы «Катерина» за авторством Тараса Шевченко, где фигурировало слово «Москаль». Многие в защиту разработчиков говорили, что это просто дань уважения великому автору. Но разве колба с мутантом в жёлтой жиже — это подходящее место для такого?

добавить пикчу 
![EdpGzRIWkAAuGK4 png_large](https://user-images.githubusercontent.com/33309477/105052216-0ffa1880-5a89-11eb-91a9-adc662db82e8.png)

**Comment by stalker-thread** [comment]
Добавлю

**Comment by stalker-thread** [comment]
Добавлено
