### ISSUE TITLE
Создать конфу на время обезумевшего мерцающего

### ISSUE THREAD

**Issue by Dmitriy000** [stalker-thread/stalker-thread.github.io#8]
Ну или я хз что сделать, он там перебанил пол треда точно

**Comment by c1p-it** [comment]
Хуя ты шизло

**Comment by Dmitriy000** [comment]
Гаргамель и сюда добрался
Архивариус выручай

**Comment by c1p-it** [comment]
@Dmitriy000 я не гергашлюй. Нахуя конфа? Здесь сиди, гитхуб отлично подходит для общения.

**Comment by stalker-thread** [comment]
Создавайте. Я здесь причём?

**Comment by Dmitriy000** [comment]
Ну а ты что предлагаешь делать? в д всем похуй видимо, уже вторую неделю воюем. А модер только сильней лютует и всё ему сходит с рук. 

Ты при том что на сайт можешь на главную добавить инфу про перекат в новое место, потому что в треде всё потрётся.
Как ты заметил, мочер и шапку даже редачить не стесняется

**Comment by stalker-thread** [comment]
@Dmitriy000 ну вот будет ссылка — неси, добавлю.
